flags: {}
extra-package-dbs: []
packages:
  - location: '.'
  - location:
      git: https://github.com/samtay/byline.git
      commit: c51f3de4e674e5de5199a1b7fbf4e8d73ee8ed97
    extra-dep: true
extra-deps:
- optparse-applicative-0.14.0.0
- terminfo-hs-0.2.1
resolver: lts-9.0
