flags: {}
extra-package-dbs: []
packages:
  - location: '.'
  - location:
      git: git@github.com:samtay/byline.git
      commit: 0c614726b33d59d64eba11cc0d94d5696b33c858
    extra-dep: true
extra-deps:
- optparse-applicative-0.14.0.0
- terminfo-hs-0.2.1
resolver: lts-8.21
