flags: {}
extra-package-dbs: []
packages:
- .
extra-deps:
- ansi-terminal-0.10.3
- terminfo-hs-0.2.1
- git: https://github.com/samtay/byline.git
  commit: ac64db655f46f55406762e08e5942fb031c41774

resolver: lts-14.25
